# coding=utf-8
# thanks 皮zy
import mod.client.extraClientApi as clientApi

minecraftEnum = clientApi.GetMinecraftEnum()

# 键盘按键中文映射表
KEYBOARD_STR_MAPPING = {
    minecraftEnum.KeyBoardType.KEY_MOUSE_LEFT: "鼠标左键",
    minecraftEnum.KeyBoardType.KEY_MOUSE_RIGHT: "鼠标右键",
    minecraftEnum.KeyBoardType.KEY_MOUSE_Middle: "鼠标中键",
    minecraftEnum.KeyBoardType.KEY_BACKSPACE: "Backspace",
    minecraftEnum.KeyBoardType.KEY_TAB: "Tab",
    minecraftEnum.KeyBoardType.KEY_RETURN: "回车",
    minecraftEnum.KeyBoardType.KEY_PAUSE: "Pause",
    minecraftEnum.KeyBoardType.KEY_LSHIFT: "Shift",
    minecraftEnum.KeyBoardType.KEY_CONTROL: "Ctrl",
    minecraftEnum.KeyBoardType.KEY_MENU: "Alt",
    minecraftEnum.KeyBoardType.KEY_CAPS_LOCK: "Caps Lock",
    minecraftEnum.KeyBoardType.KEY_ESCAPE: "Esc",
    minecraftEnum.KeyBoardType.KEY_SPACE: "空格",
    minecraftEnum.KeyBoardType.KEY_PG_UP: "Page Up",
    minecraftEnum.KeyBoardType.KEY_PG_DOWN: "Page Down",
    minecraftEnum.KeyBoardType.KEY_END: "End",
    minecraftEnum.KeyBoardType.KEY_HOME: "Home",
    minecraftEnum.KeyBoardType.KEY_LEFT: "←",
    minecraftEnum.KeyBoardType.KEY_UP: "↑",
    minecraftEnum.KeyBoardType.KEY_RIGHT: "→",
    minecraftEnum.KeyBoardType.KEY_DOWN: "↓",
    minecraftEnum.KeyBoardType.KEY_INSERT: "Insert",
    minecraftEnum.KeyBoardType.KEY_DELETE: "Delete",
    minecraftEnum.KeyBoardType.KEY_0: "0",
    minecraftEnum.KeyBoardType.KEY_1: "1",
    minecraftEnum.KeyBoardType.KEY_2: "2",
    minecraftEnum.KeyBoardType.KEY_3: "3",
    minecraftEnum.KeyBoardType.KEY_4: "4",
    minecraftEnum.KeyBoardType.KEY_5: "5",
    minecraftEnum.KeyBoardType.KEY_6: "6",
    minecraftEnum.KeyBoardType.KEY_7: "7",
    minecraftEnum.KeyBoardType.KEY_8: "8",
    minecraftEnum.KeyBoardType.KEY_9: "9",
    minecraftEnum.KeyBoardType.KEY_A: "A",
    minecraftEnum.KeyBoardType.KEY_B: "B",
    minecraftEnum.KeyBoardType.KEY_C: "C",
    minecraftEnum.KeyBoardType.KEY_D: "D",
    minecraftEnum.KeyBoardType.KEY_E: "E",
    minecraftEnum.KeyBoardType.KEY_F: "F",
    minecraftEnum.KeyBoardType.KEY_G: "G",
    minecraftEnum.KeyBoardType.KEY_H: "H",
    minecraftEnum.KeyBoardType.KEY_I: "I",
    minecraftEnum.KeyBoardType.KEY_J: "J",
    minecraftEnum.KeyBoardType.KEY_K: "K",
    minecraftEnum.KeyBoardType.KEY_L: "L",
    minecraftEnum.KeyBoardType.KEY_M: "M",
    minecraftEnum.KeyBoardType.KEY_N: "N",
    minecraftEnum.KeyBoardType.KEY_O: "O",
    minecraftEnum.KeyBoardType.KEY_P: "P",
    minecraftEnum.KeyBoardType.KEY_Q: "Q",
    minecraftEnum.KeyBoardType.KEY_R: "R",
    minecraftEnum.KeyBoardType.KEY_S: "S",
    minecraftEnum.KeyBoardType.KEY_T: "T",
    minecraftEnum.KeyBoardType.KEY_U: "U",
    minecraftEnum.KeyBoardType.KEY_V: "V",
    minecraftEnum.KeyBoardType.KEY_W: "W",
    minecraftEnum.KeyBoardType.KEY_X: "X",
    minecraftEnum.KeyBoardType.KEY_Y: "Y",
    minecraftEnum.KeyBoardType.KEY_Z: "Z",
    minecraftEnum.KeyBoardType.KEY_NUMPAD0: ">0",
    minecraftEnum.KeyBoardType.KEY_NUMPAD1: ">1",
    minecraftEnum.KeyBoardType.KEY_NUMPAD2: ">2",
    minecraftEnum.KeyBoardType.KEY_NUMPAD3: ">3",
    minecraftEnum.KeyBoardType.KEY_NUMPAD4: ">4",
    minecraftEnum.KeyBoardType.KEY_NUMPAD5: ">5",
    minecraftEnum.KeyBoardType.KEY_NUMPAD6: ">6",
    minecraftEnum.KeyBoardType.KEY_NUMPAD7: ">7",
    minecraftEnum.KeyBoardType.KEY_NUMPAD8: ">8",
    minecraftEnum.KeyBoardType.KEY_NUMPAD9: ">9",
    minecraftEnum.KeyBoardType.KEY_MULTIPLY: "×",
    minecraftEnum.KeyBoardType.KEY_ADD: "+",
    minecraftEnum.KeyBoardType.KEY_SUBTRACT: "-",
    minecraftEnum.KeyBoardType.KEY_DECIMAL: "小数点",
    minecraftEnum.KeyBoardType.KEY_DIVIDE: "/",
    minecraftEnum.KeyBoardType.KEY_F1: "F1",
    minecraftEnum.KeyBoardType.KEY_F2: "F2",
    minecraftEnum.KeyBoardType.KEY_F3: "F3",
    minecraftEnum.KeyBoardType.KEY_F4: "F4",
    minecraftEnum.KeyBoardType.KEY_F5: "F5",
    minecraftEnum.KeyBoardType.KEY_F6: "F6",
    minecraftEnum.KeyBoardType.KEY_F7: "F7",
    minecraftEnum.KeyBoardType.KEY_F8: "F8",
    minecraftEnum.KeyBoardType.KEY_F9: "F9",
    minecraftEnum.KeyBoardType.KEY_F10: "F10",
    minecraftEnum.KeyBoardType.KEY_F11: "F11",
    minecraftEnum.KeyBoardType.KEY_F12: "F12",
    minecraftEnum.KeyBoardType.KEY_F13: "F13",
    minecraftEnum.KeyBoardType.KEY_NUM_LOCK: "Num Lock",
    minecraftEnum.KeyBoardType.KEY_SCROLL: "Scroll Lock",
    minecraftEnum.KeyBoardType.KEY_SEMICOLON: ";",
    minecraftEnum.KeyBoardType.KEY_EQUALS: "=",
    minecraftEnum.KeyBoardType.KEY_COMMA: ",",
    minecraftEnum.KeyBoardType.KEY_MINUS: "-",
    minecraftEnum.KeyBoardType.KEY_PERIOD: ".",
    minecraftEnum.KeyBoardType.KEY_SLASH: "/",
    minecraftEnum.KeyBoardType.KEY_GRAVE: "`",
    minecraftEnum.KeyBoardType.KEY_LBRACKET: "[",
    minecraftEnum.KeyBoardType.KEY_BACKSLASH: "\\",
    minecraftEnum.KeyBoardType.KEY_RBRACKET: "]",
    minecraftEnum.KeyBoardType.KEY_APOSTRAPHE: "'",
}

# 游戏手柄按键中文映射表
GAMEPAD_STR_MAPPING = {
    minecraftEnum.GamepadKeyType.UNDEFINED: "",
    minecraftEnum.GamepadKeyType.KEY_A: "A",
    minecraftEnum.GamepadKeyType.KEY_B: "B",
    minecraftEnum.GamepadKeyType.KEY_X: "X",
    minecraftEnum.GamepadKeyType.KEY_Y: "Y",
    minecraftEnum.GamepadKeyType.KEY_DPAD_UP: "↑",
    minecraftEnum.GamepadKeyType.KEY_DPAD_DOWN: "↓",
    minecraftEnum.GamepadKeyType.KEY_DPAD_LEFT: "←",
    minecraftEnum.GamepadKeyType.KEY_DPAD_RIGHT: "→",
    minecraftEnum.GamepadKeyType.KEY_LS: "LS",
    minecraftEnum.GamepadKeyType.KEY_RS: "RS",
    minecraftEnum.GamepadKeyType.KEY_LB: "LB",
    minecraftEnum.GamepadKeyType.KEY_RB: "RB",
    minecraftEnum.GamepadKeyType.KEY_VIEW: "VIEW",
    minecraftEnum.GamepadKeyType.KEY_MENU: "MENU",
    minecraftEnum.GamepadKeyType.STICK_LEFT: "左摇杆",
    minecraftEnum.GamepadKeyType.STICK_RIGHT: "右摇杆",
    minecraftEnum.GamepadKeyType.TRIGGER_LEFT: "左扳机",
    minecraftEnum.GamepadKeyType.TRIGGER_RIGHT: "右扳机",
}
